site_name: TerraME




theme:
  name: readthedocs
  custom_dir: overrides
  logo: img/terrameee.png
  site_favicon: img/favicon.ico
  highlightjs: true
  extra_css: 
    - css/extra.css


nav:
  - TerraME: 
    - 'index.md'
  - Base: 
    - Index: 'base/index.md'
    - Types:
      - Agent: 'base/types/agent.md'
      - Automaton: 'base/types/automaton.md'
      - Cell: 'base/types/cell.md'
      - CellularSpace: 'base/types/cellularSpace.md'
      - Chart: 'base/types/chart.md'
      - Choice: 'base/types/choice.md'
      - Clock: 'base/types/clock.md'
      - DataFrame: 'base/types/dataFrame.md'
      - Directory: 'base/types/directory.md'
      - Environment: 'base/types/environment.md'
      - Event: 'base/types/event.md'
      - File: 'base/types/file.md'
      - Flow: 'base/types/flow.md'
      - Group: 'base/types/group.md'
      - InternetSender: 'base/types/internetSender.md'
      - Jump: 'base/types/jump.md'
      - Log: 'base/types/log.md'
      - Mandatory: 'base/types/mandatory.md'
      - Map: 'base/types/map.md'
      - Model: 'base/types/model.md'
      - Neighborhood: 'base/types/neighborhood.md'
      - Profiler: 'base/types/profiler.md'
      - Random: 'base/types/random.md'
      - SocialNetwork: 'base/types/socialNetwork.md'
      - Society: 'base/types/society.md'
      - State: 'base/types/state.md'
      - TextScreen: 'base/types/textScreen.md'
      - Timer: 'base/types/timer.md'
      - Trajectory: 'base/types/trajectory.md'
      - UnitTest: 'base/types/unitTest.md'
      - VisualTable: 'base/types/visualTable.md'
    - Functions:
      - ErrorHandling: 'base/functions/errorHandling.md'
      - Os: 'base/functions/os.md'
      - Package: 'base/functions/package.md'
      - Utils: 'base/functions/utils.md'
    - Examples: 'base/examples.md'
    - Data: 'base/data.md'
    - Font: 'base/font.md'
  - gis:
    - gis: 'package/gis/index.md'
    - Types:
        - Layer: 'package/gis/types/layer.md'
        - Project: 'package/gis/types/project.md'
        - TerraLib: 'package/gis/types/terralib.md'
    - Functions:
        - Utils: 'package/gis/functions/utils.md'
        - Examples: 'package/gis/functions/examples.md'
        - Data: 'package/gis/functions/data.md'
  - ca:
    - ca: 'package/ca/index.md'
    - Models: 'package/ca/models.md'
    - Functions:
      - LifePatterns: 'package/ca/functions/lifePatterns.md' 
      - Utils: 'package/ca/functions/utils.md'
      - Examples: 'package/ca/functions/examples.md'
      - Data: 'package/ca/functions/data.md'
  - logo:
    - logo: 'package/logo/index.md'
    - Models: 'package/logo/models.md'
    - Functions:
      - Utils: 'package/logo/functions/utils.md'
      - Examples: 'package/logo/functions/examples.md'
      - Data: 'package/logo/functions/data.md'
  - sci:
    - sci: 'package/sci/index.md'
    - Types:
      - Spline: 'package/sci/types/spline.md'
    - Functions:
      - Feedback: 'package/sci/functions/feedback.md'
      - Examples: 'package/sci/functions/examples.md'
  - sysdyn:
    - sysdyn: 'package/sysdyn/index.md'
    - Models: 'package/sysdyn/models.md'
    - Examples: 'package/sysdyn/examples.md'
  - calibration:
    - calibration: 'package/calibration/index.md'
    - Types:
      - MultipleRuins: 'package/calibration/types/multipleRuins.md'
      - SAMDE: 'package/calibration/types/samde.md'
    - Functions:
      - GoodnessOfFit: 'package/calibration/functions/goodnessOfFit.md'
      - Utils: 'package/calibration/functions/utils.md'
      - Examples: 'package/calibration/functions/examples.md'
      - Data: 'package/calibration/functions/data.md'
  - gpm:
    - gpm: 'package/gpm/index.md'
    - Types:
      - GPM: 'package/gpm/types/gpm.md'
      - Network: 'package/gpm/types/network.md'
      - Example: 'package/gpm/types/examples.md'
      - Data: 'package/gpm/types/data.md'
  - Publish:
    - Publish: 'package/publish/index.md'
    - Types:
      - Application: 'package/publish/types/application.md'
      - List: 'package/publish/types/list.md'
      - Report: 'package/publish/types/report.md'
      - View: 'package/publish/types/view.md'
    - Functions:
      - Color: 'package/publish/functions/color.md'
      - Utils: 'package/publish/functions/utils.md'
      - Examples: 'package/publish/functions/examples.md'
      - Data: 'package/publish/functions/data.md'
      

  #   - Package-list: 'package/package-list.md'

markdown_extensions:

  #pymdown
  - pymdownx.tasklist # Lista de tarefas
  - pymdownx.emoji
      # emoji_index: !!python/name:material.extensions.emoji.twemoji
      # emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.mark # Marcações
  - pymdownx.tilde # Tachado
  - pymdownx.highlight # código
  - pymdownx.superfences #bloquinho

  - tables
  - attr_list



copyright: Copyright &copy; 2025 TerraME